### ISSUE TITLE
exception error on OSX

### ISSUE THREAD

**Issue by Enrico68** [joidegn/leo-cli#18]
Step to reproduce : 

`leo -i Arzt`

```
doctor/der Arzt (die Ärzte, die Ärztinnen)
Noun
===Deklination - bestimmt===
Singular              Plural
--------------------  ---------------------
---------  ---------  ---------  ----------
Nominativ  der Arzt   Nominativ  die Ärzte
Genitiv    des Arzts  Genitiv    der Ärzte
Dativ      dem Arzt   Dativ      den Ärzten
Akkusativ  den Arzt   Akkusativ  die Ärzte
---------  ---------  ---------  ----------
Traceback (most recent call last):
  File "/usr/local/bin/leo", line 277, in _pairwise
    x = next(it)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/leo", line 364, in <module>
    _print_inflection_table(table)
  File "/usr/local/bin/leo", line 304, in _print_inflection_table
    for x, y in _pairwise(mood['variants']):
RuntimeError: generator raised StopIteration
```
 This happen  just on OSX ,

**Comment by rezarahimi** [comment]
I have the same exception on Linux(Ubuntu)
```
leo -i Arzt
doctor/der Arzt (die Ärzte, die Ärztinnen)
Noun
===Deklination - bestimmt===
Singular              Plural
--------------------  ---------------------
---------  ---------  ---------  ----------
Nominativ  der Arzt   Nominativ  die Ärzte
Genitiv    des Arzts  Genitiv    der Ärzte
Dativ      dem Arzt   Dativ      den Ärzten
Akkusativ  den Arzt   Akkusativ  die Ärzte
---------  ---------  ---------  ----------
Traceback (most recent call last):
  File "$HOME/.pyenv/versions/3.7.0/bin/leo", line 277, in _pairwise
    x = next(it)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "$HOME/.pyenv/versions/3.7.0/bin/leo", line 364, in <module>
    _print_inflection_table(table)
  File "$HOME/.pyenv/versions/3.7.0/bin/leo", line 304, in _print_inflection_table
    for x, y in _pairwise(mood['variants']):
RuntimeError: generator raised StopIteration
```
Environments:
```
$ pyenv versions
 system
 2.7.15
* 3.7.0 (set by $HOME/.pyenv/version)
```
```
$ pyenv global
3.7.0
```
```
$ python --version
Python 3.7.0
$ lsb_release -a  
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```
```
$ uname -a        
Linux my-pc 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
