### ISSUE TITLE
Error on Ubuntu 20.04.2, while using leo

### ISSUE THREAD

**Issue by anishmittal2020** [joidegn/leo-cli#22]
# Installation

```bash
$ pipx install leo-cli
  installed package leo-cli 0.3.6, Python 3.8.10
  These apps are now globally available
    - leo
done! ✨ 🌟 ✨
```

# Issue

```bash
$ leo example
Traceback (most recent call last):
  File "/home/nikhil/.local/bin/leo", line 348, in <module>
    entries = get_entries(word, args['source_lang'], args['pos'], verbose=args['verbose'])
  File "/home/nikhil/.local/bin/leo", line 59, in get_entries
    entries = _retrieve_translation_doc(word, source_lang, verbose=verbose).find_all('entry')
  File "/home/nikhil/.local/bin/leo", line 116, in _retrieve_translation_doc
    return requestManager.get_xml(url, verbose=verbose)
  File "/home/nikhil/.local/bin/leo", line 53, in get_xml
    soup = BeautifulSoup(r.text, 'lxml')
  File "/home/nikhil/.local/pipx/venvs/leo-cli/lib/python3.8/site-packages/bs4/__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

**Comment by joidegn** [comment]
Hey @anishmittal2020 , thanks for reporting. Normally this error is fixed by installing lxml but I just tried to verify your steps in an ubuntu 20.04 docker container and that did not seem to fix the issue.

This commit should fix it and remove the dependency on lxml.
https://github.com/joidegn/leo-cli/commit/9dd2b6152293793d66236c25d6063b22732d08c5

**Comment by anishmittal2020** [comment]
@joidegn  Hi! May I suggest that you could also install using [pypa/pipx: Install and Run Python Applications in Isolated Environments](https://github.com/pypa/pipx).

```bash
$ pipx install leo-cli
  installed package leo-cli 0.3.7, Python 3.8.10
  These apps are now globally available
    - leo
done! ✨ 🌟 ✨
```

### Issue

```bash
$ leo example
Traceback (most recent call last):
  File "/home/nikhil/.local/bin/leo", line 21, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```
